version: '2'
services:
    smartcpd-app:
        image: smartcpd
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartcpd-mysql:3306/smartcpd?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=smartcpd-elasticsearch:9300
        ports:
            - 8080:8080
    smartcpd-mysql:
        extends:
            file: mysql.yml
            service: smartcpd-mysql
    smartcpd-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smartcpd-elasticsearch
