version: '2'
services:
    smartcpd-elasticsearch:
        image: elasticsearch:6.8.0
        # volumes:
        #     - ~/volumes/jhipster/SmartCPD/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
        environment:
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
